"""Create initial tables

Revision ID: 25c8f48abee5
Revises: 
Create Date: 2025-12-10 15:54:20.158268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '25c8f48abee5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 获取连接以检查索引和表是否存在
    connection = op.get_bind()
    
    def table_exists(table_name: str) -> bool:
        """检查表是否存在"""
        from sqlalchemy import text as sql_text
        result = connection.execute(
            sql_text("""
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = :table_name
            """),
            {"table_name": table_name}
        )
        return result.fetchone() is not None
    
    def index_exists(index_name: str) -> bool:
        """检查索引是否存在"""
        from sqlalchemy import text as sql_text
        result = connection.execute(
            sql_text("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = :index_name
            """),
            {"index_name": index_name}
        )
        return result.fetchone() is not None
    
    def create_index_if_not_exists(index_name: str, table_name: str, columns: list, **kwargs):
        """如果索引不存在则创建"""
        if not index_exists(index_name):
            if isinstance(columns, str):
                op.create_index(index_name, table_name, [columns], **kwargs)
            else:
                op.create_index(index_name, table_name, columns, **kwargs)
    
    def drop_table_if_exists(table_name: str):
        """如果表存在则删除"""
        if table_exists(table_name):
            op.drop_table(table_name)
    
    def drop_index_if_exists(index_name: str, table_name: str, **kwargs):
        """如果索引存在则删除"""
        if index_exists(index_name):
            try:
                # 尝试使用 op.f() 方式（适用于 Alembic 自动生成的索引名）
                op.drop_index(op.f(index_name), table_name=table_name, **kwargs)
            except Exception:
                # 如果失败，尝试直接使用索引名
                try:
                    op.drop_index(index_name, table_name=table_name, **kwargs)
                except Exception:
                    # 如果还是失败，忽略（索引可能不存在或名称不匹配）
                    pass
    
    op.create_table('ai_interaction_records',
    sa.Column('record_id', sa.String(length=64), nullable=False, comment='记录唯一标识'),
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组ID'),
    sa.Column('user_message_id', sa.String(length=64), nullable=False, comment='用户消息ID'),
    sa.Column('ai_message_id', sa.String(length=64), nullable=True, comment='AI回复消息ID'),
    sa.Column('ai_service_url', sa.String(length=256), nullable=True, comment='AI服务URL'),
    sa.Column('request_content', sa.Text(), nullable=True, comment='请求内容（JSON格式）'),
    sa.Column('response_content', sa.Text(), nullable=True, comment='响应内容（JSON格式）'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态：0-处理中，1-成功，2-失败'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='处理耗时（毫秒）'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    create_index_if_not_exists('idx_created_at', 'ai_interaction_records', ['created_at'], unique=False)
    create_index_if_not_exists('idx_group_id', 'ai_interaction_records', ['group_id'], unique=False)
    create_index_if_not_exists('idx_status', 'ai_interaction_records', ['status'], unique=False)
    create_index_if_not_exists('idx_user_message_id', 'ai_interaction_records', ['user_message_id'], unique=False)
    create_index_if_not_exists('ix_ai_interaction_records_id', 'ai_interaction_records', ['id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组ID'),
    sa.Column('user_id', sa.String(length=48), nullable=False, comment='用户ID'),
    sa.Column('user_role', sa.String(length=32), nullable=False, comment='用户在群组中的身份标签：PATIENT/DOCTOR/AI_ASSISTANT'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='加入时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uk_group_user')
    )
    create_index_if_not_exists('idx_group_id', 'group_members', ['group_id'], unique=False)
    create_index_if_not_exists('idx_user_id', 'group_members', ['user_id'], unique=False)
    create_index_if_not_exists('idx_user_role', 'group_members', ['user_role'], unique=False)
    create_index_if_not_exists('ix_group_members_id', 'group_members', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组唯一标识'),
    sa.Column('group_name', sa.String(length=128), nullable=False, comment='群组名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='群组描述'),
    sa.Column('created_by', sa.String(length=48), nullable=False, comment='创建人ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    create_index_if_not_exists('idx_created_by', 'groups', ['created_by'], unique=False)
    create_index_if_not_exists('idx_group_id', 'groups', ['group_id'], unique=False)
    create_index_if_not_exists('ix_groups_id', 'groups', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=64), nullable=False, comment='消息唯一标识'),
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组ID'),
    sa.Column('from_user_id', sa.String(length=48), nullable=False, comment='发送人ID'),
    sa.Column('msg_type', sa.String(length=32), nullable=False, comment='消息类型：TEXT(文本)/IMAGE(图片)/AI_REPLY(AI回复)'),
    sa.Column('msg_content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    create_index_if_not_exists('idx_created_at', 'messages', ['created_at'], unique=False)
    create_index_if_not_exists('idx_from_user_id', 'messages', ['from_user_id'], unique=False)
    create_index_if_not_exists('idx_group_created', 'messages', ['group_id', 'created_at'], unique=False)
    create_index_if_not_exists('idx_group_id', 'messages', ['group_id'], unique=False)
    create_index_if_not_exists('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=48), nullable=False, comment='用户唯一标识'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('user_role', sa.String(length=32), nullable=False, comment='用户身份：PATIENT(患者)/DOCTOR(医生)/AI_ASSISTANT(医生AI助手)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    create_index_if_not_exists('idx_user_id', 'users', ['user_id'], unique=False)
    create_index_if_not_exists('idx_user_role', 'users', ['user_role'], unique=False)
    create_index_if_not_exists('ix_users_id', 'users', ['id'], unique=False)
    
    # 删除旧表（如果存在）- 这些表是从其他项目迁移过来的，在新数据库中可能不存在
    drop_table_if_exists('checkpoint_migrations')
    drop_table_if_exists('test_sqlalchemy_setup')
    drop_table_if_exists('store_migrations')
    drop_index_if_exists('idx_blood_pressure_measurement_time', 'blood_pressure_records')
    drop_index_if_exists('idx_blood_pressure_user_id', 'blood_pressure_records')
    drop_index_if_exists('idx_blood_pressure_user_time', 'blood_pressure_records')
    drop_table_if_exists('blood_pressure_records')
    drop_index_if_exists('internal_medicine_kb_embedding_hnsw_idx', 'internal_medicine_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    drop_table_if_exists('internal_medicine_kb')
    drop_index_if_exists('test_rag_flow_embedding_hnsw_idx', 'test_rag_flow', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    drop_table_if_exists('test_rag_flow')
    drop_index_if_exists('cardiology_kb_embedding_hnsw_idx', 'cardiology_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    drop_table_if_exists('cardiology_kb')
    drop_index_if_exists('checkpoint_writes_thread_id_idx', 'checkpoint_writes')
    drop_table_if_exists('checkpoint_writes')
    drop_index_if_exists('idx_appointments_appointment_date', 'appointments')
    drop_index_if_exists('idx_appointments_status', 'appointments')
    drop_index_if_exists('idx_appointments_user_id', 'appointments')
    drop_index_if_exists('idx_appointments_user_status', 'appointments')
    drop_table_if_exists('appointments')
    drop_index_if_exists('surgery_kb_embedding_hnsw_idx', 'surgery_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    drop_table_if_exists('surgery_kb')
    drop_index_if_exists('gynecology_kb_embedding_hnsw_idx', 'gynecology_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    drop_table_if_exists('gynecology_kb')
    drop_index_if_exists('pediatrics_kb_embedding_hnsw_idx', 'pediatrics_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    drop_table_if_exists('pediatrics_kb')
    drop_index_if_exists('idx_store_expires_at', 'store', postgresql_where='(expires_at IS NOT NULL)')
    drop_index_if_exists('store_prefix_idx', 'store', postgresql_ops={'prefix': 'text_pattern_ops'})
    drop_table_if_exists('store')
    drop_index_if_exists('general_diagnosis_kb_embedding_hnsw_idx', 'general_diagnosis_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    drop_table_if_exists('general_diagnosis_kb')
    drop_index_if_exists('checkpoints_thread_id_idx', 'checkpoints')
    drop_table_if_exists('checkpoints')
    drop_index_if_exists('checkpoint_blobs_thread_id_idx', 'checkpoint_blobs')
    drop_table_if_exists('checkpoint_blobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('general_diagnosis_kb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('general_diagnosis_kb_pkey'))
    )
    op.create_index(op.f('general_diagnosis_kb_embedding_hnsw_idx'), 'general_diagnosis_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name=op.f('store_pkey'))
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, postgresql_ops={'prefix': 'text_pattern_ops'})
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('pediatrics_kb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pediatrics_kb_pkey'))
    )
    op.create_index(op.f('pediatrics_kb_embedding_hnsw_idx'), 'pediatrics_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('gynecology_kb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gynecology_kb_pkey'))
    )
    op.create_index(op.f('gynecology_kb_embedding_hnsw_idx'), 'gynecology_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('surgery_kb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('surgery_kb_pkey'))
    )
    op.create_index(op.f('surgery_kb_embedding_hnsw_idx'), 'surgery_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doctor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('appointments_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('idx_appointments_user_status'), 'appointments', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_index(op.f('idx_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('idx_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('cardiology_kb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cardiology_kb_pkey'))
    )
    op.create_index(op.f('cardiology_kb_embedding_hnsw_idx'), 'cardiology_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('test_rag_flow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_rag_flow_pkey'))
    )
    op.create_index(op.f('test_rag_flow_embedding_hnsw_idx'), 'test_rag_flow', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('internal_medicine_kb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('internal_medicine_kb_pkey'))
    )
    op.create_index(op.f('internal_medicine_kb_embedding_hnsw_idx'), 'internal_medicine_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('blood_pressure_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('systolic', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diastolic', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('measurement_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('original_time_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('diastolic >= 30 AND diastolic <= 200', name=op.f('blood_pressure_records_diastolic_check')),
    sa.CheckConstraint('systolic > diastolic', name=op.f('check_systolic_gt_diastolic')),
    sa.CheckConstraint('systolic >= 50 AND systolic <= 300', name=op.f('blood_pressure_records_systolic_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('blood_pressure_records_pkey'))
    )
    op.create_index(op.f('idx_blood_pressure_user_time'), 'blood_pressure_records', ['user_id', 'measurement_time'], unique=False)
    op.create_index(op.f('idx_blood_pressure_user_id'), 'blood_pressure_records', ['user_id'], unique=False)
    op.create_index(op.f('idx_blood_pressure_measurement_time'), 'blood_pressure_records', ['measurement_time'], unique=False)
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    op.create_table('test_sqlalchemy_setup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_sqlalchemy_setup_pkey'))
    )
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('idx_group_id', table_name='messages')
    op.drop_index('idx_group_created', table_name='messages')
    op.drop_index('idx_from_user_id', table_name='messages')
    op.drop_index('idx_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index('idx_group_id', table_name='groups')
    op.drop_index('idx_created_by', table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.drop_index('idx_user_role', table_name='group_members')
    op.drop_index('idx_user_id', table_name='group_members')
    op.drop_index('idx_group_id', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_ai_interaction_records_id'), table_name='ai_interaction_records')
    op.drop_index('idx_user_message_id', table_name='ai_interaction_records')
    op.drop_index('idx_status', table_name='ai_interaction_records')
    op.drop_index('idx_group_id', table_name='ai_interaction_records')
    op.drop_index('idx_created_at', table_name='ai_interaction_records')
    op.drop_table('ai_interaction_records')
    # ### end Alembic commands ###

